targets:
  ubuntu-12.04:
    build_dependencies:
      - libopencv-dev
      - cmake
    dependencies:
      - libopencv-objdetect2.3
  ubuntu-14.04:
    build_dependencies:
      - libopencv-dev
      - cmake
    dependencies:
      - libopencv-objdetect2.4
buildpack: https://github.com/pkgr/pkgr-noop-buildpack
user: catcierge
group: catcierge
before:
  - git submodule sync
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -DRPI=OFF ..
  - cmake --build .
