env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Kza1lOgpHML3DiiKuRUji0xHXmDxsfMSxHgff/WR6+nOlubNpWUmf1OwWe4BBTX8GblKPXOlWFpzPtwA5l1NiT2rQ/s7ypsmCS16bGppV34VC77iJSAT6qrqao7Wb3iziRbtba5rVfiqHtEYJLw2q5psz9JcjI+G7On25jciM4M="
  matrix:
   - CAT_METHOD=memcheck
   - CAT_METHOD=coverage CMAKE_ARGS="-DCATCIERGE_WITH_MEMCHECK=OFF -DCATCIERGE_COVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DCATCIERGE_GUI_TESTS=ON" COVERALLS=yes
language: c
sudo: false
os:
  - linux
  - osx
before_install:
  # Enable running GUI tests to run with a dummy X-server.
  - if [ x$TRAVIS_OS_NAME == xlinux ]; then export DISPLAY=:99.0; fi
  - if [ x$TRAVIS_OS_NAME == xlinux ]; then sh -e /etc/init.d/xvfb start; fi
install:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xlinux ]; then apt-get update -qq && apt-get install -y -qq libopencv-dev; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xlinux ]; then apt-get update -qq && apt-get install -y -qq lcov valgrind; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xlinux ]; then apt-get update -qq && apt-get install -y -qq lcov valgrind; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xosx ]; then brew tap homebrew/science && brew update && brew install opencv; fi
script:
  # Only run coverage on Linux/gcc.
  - if [ x$CAT_METHOD == xcoverage ] && [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xlinux ]; then mkdir build && cd build && cmake -DRPI=0 $CMAKE_ARGS .. && cmake --build . && cmake --build . --target coveralls; fi
  - if [ x$CAT_METHOD == xmemcheck ] && [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xlinux ]; then mkdir build && cd build && cmake -DRPI=0 $CMAKE_ARGS .. && cmake --build . && ctest --output-on-failure; fi
  - if [ x$CAT_METHOD == xmemcheck ] && [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ x$TRAVIS_OS_NAME == xosx ]; then mkdir build && cd build && cmake -DRPI=0 -DOpenCV_DIR=/usr/local/Cellar/opencv/2.4.9/build $CMAKE_ARGS .. && cmake --build . && ctest --output-on-failure; fi

addons:
  coverity_scan:
    project:
      name: "JoakimSoderberg/catcierge"
    notification_email: joakim.soderberg@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DRPI=OFF -DCATCIERGE_WITH_MEMCHECK=OFF .."
    build_command: "cmake --build ."
    branch_pattern: coverity_scan
