
#include <assert.h>
#include "catcierge_haar_matcher.h"
#include "catcierge_haar_wrapper.h"

int catcierge_haar_matcher_init(catcierge_haar_matcher_t *ctx, catcierge_haar_matcher_args_t *args)
{
	assert(args);
	assert(ctx);

	if (!args->cascade)
	{
		return -1;
	}

	if (!(ctx->cascade = cv2CascadeClassifier_create()))
	{
		return -1;
	}

	if (cv2CascadeClassifier_load(ctx->cascade, args->cascade))
	{
		return -1;
	}

	return 0;
}

void catcierge_haar_matcher_destroy(catcierge_haar_matcher_t *ctx)
{
	assert(ctx);
	if (ctx->cascade)
	{
		cv2CascadeClassifier_destroy(ctx->cascade);
	}
}

double catcierge_haar_matcher_match(catcierge_haar_matcher_t *ctx, const IplImage *img,
		CvRect *match_rects, size_t *rect_count)
{
	assert(ctx);
	CvSize max_size;
	CvSize min_size;
	min_size.width = 80;
	min_size.height = 80;
	max_size.width = 200;
	max_size.height = 200;

	if (cv2CascadeClassifier_detectMultiScale(ctx->cascade,
			img, match_rects, rect_count,
			1.1, 3, 0, &min_size, &max_size))
	{
		return -1.0;
	}

	printf("Rect count: %zu\n", *rect_count);

	return (*rect_count > 0) ? 1.0 : 0.0;
}

void catcierge_haar_matcher_usage()
{
	fprintf(stderr, " --cascade <path>       Path to the haar cascade xml generated by opencv_traincascade.\n");
	fprintf(stderr, " --min_size <WxH>       The size of the minimum\n");
	fprintf(stderr, "\n");
}

int catcierge_haar_matcher_parse_args(catcierge_haar_matcher_args_t *args, const char *key, char **values, size_t value_count)
{
	printf("Parse: %s %s", key, values[0]);
	if (!strcmp(key, "cascade"))
	{
		if (value_count == 1)
		{
			args->cascade = values[0];
		}
		else
		{
			fprintf(stderr, "Missing value for --cascade\n");
			return -1;
		}

		return 0;
	}

	if (!strcmp(key, "min_size"))
	{
		if (value_count == 1)
		{
			if (sscanf(values[0], "%dx%d", &args->min_width, &args->min_height) == EOF)
			{
				fprintf(stderr, "Invalid format for --min_size \"%s\"\n", values[0]);
				return -1;
			}
		}
		else
		{
			fprintf(stderr, "Missing value for --min_size\n");
			return -1;
		}

		return 0;
	}

	return 1;
}

void catcierge_haar_matcher_print_settings(catcierge_haar_matcher_args_t *args)
{
	assert(args);
	printf("Haar Cascade Matcher:\n");
	printf("    Cascade: %s\n", args->cascade);
	printf("   Min size: %dx%d\n", args->min_width, args->min_height);
	printf("\n");
}

void catcierge_haar_matcher_args_init(catcierge_haar_matcher_args_t *args)
{
	assert(args);
	memset(args, 0, sizeof(catcierge_haar_matcher_args_t));
	args->min_width = 80;
	args->min_height = 80;
}
